import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background": "rgb(var(--rgb-background) / <alpha-value>)",
        "surface": "rgb(var(--rgb-surface) / <alpha-value>)",
        "surface-secondary": "rgb(var(--rgb-surface-secondary) / <alpha-value>)",
        "surface-tertiary": "rgb(var(--rgb-surface-tertiary) / <alpha-value>)",
        "surface-muted": "rgb(var(--rgb-surface-muted) / <alpha-value>)",
        "border": "rgb(var(--rgb-border) / <alpha-value>)",
        "border-light": "rgb(var(--rgb-border-light) / <alpha-value>)",
        "border-muted": "rgb(var(--rgb-border-muted) / <alpha-value>)",
        "text-primary": "rgb(var(--rgb-text-primary) / <alpha-value>)",
        "text-secondary": "rgb(var(--rgb-text-secondary) / <alpha-value>)",
        "text-muted": "rgb(var(--rgb-text-muted) / <alpha-value>)",
        "text-dark": "rgb(var(--rgb-text-dark) / <alpha-value>)",
        "text-darker": "rgb(var(--rgb-text-darker) / <alpha-value>)",
        "text-darkest": "rgb(var(--rgb-text-darkest) / <alpha-value>)",
        "text-black": "rgb(var(--rgb-text-black) / <alpha-value>)",
        "text-slate": "rgb(var(--rgb-text-slate) / <alpha-value>)",
        "text-slate-medium": "rgb(var(--rgb-text-slate-medium) / <alpha-value>)",
        "accent": "rgb(var(--rgb-accent) / <alpha-value>)",
        "accent-dark": "rgb(var(--rgb-accent-dark) / <alpha-value>)",
        "accent-light": "rgb(var(--rgb-accent-light) / <alpha-value>)",
        "accent-muted": "rgb(var(--rgb-accent-muted) / <alpha-value>)",
        "accent-foreground": "rgb(var(--rgb-accent-foreground) / <alpha-value>)",
        "success": "rgb(var(--rgb-success) / <alpha-value>)",
        "success-alt": "rgb(var(--rgb-success-alt) / <alpha-value>)",
        "success-dark": "rgb(var(--rgb-success-dark) / <alpha-value>)",
        "success-darker": "rgb(var(--rgb-success-darker) / <alpha-value>)",
        "success-light": "rgb(var(--rgb-success-light) / <alpha-value>)",
        "success-lightest": "rgb(var(--rgb-success-lightest) / <alpha-value>)",
        "success-foreground": "rgb(var(--rgb-success-foreground) / <alpha-value>)",
        "info": "rgb(var(--rgb-info) / <alpha-value>)",
        "info-dark": "rgb(var(--rgb-info-dark) / <alpha-value>)",
        "info-medium": "rgb(var(--rgb-info-medium) / <alpha-value>)",
        "info-light": "rgb(var(--rgb-info-light) / <alpha-value>)",
        "info-lightest": "rgb(var(--rgb-info-lightest) / <alpha-value>)",
        "info-foreground": "rgb(var(--rgb-info-foreground) / <alpha-value>)",
        "info-muted": "rgb(var(--rgb-info-muted) / <alpha-value>)",
        "warning": "rgb(var(--rgb-warning) / <alpha-value>)",
        "warning-foreground": "rgb(var(--rgb-warning-foreground) / <alpha-value>)",
        "error": "rgb(var(--rgb-error) / <alpha-value>)",
        "error-foreground": "rgb(var(--rgb-error-foreground) / <alpha-value>)",
        "linkedin": "rgb(var(--rgb-linkedin) / <alpha-value>)",
        "linkedin-light": "rgb(var(--rgb-linkedin-light) / <alpha-value>)",
        "linkedin-foreground": "rgb(var(--rgb-linkedin-foreground) / <alpha-value>)",
        "overlay": "rgb(var(--rgb-overlay) / <alpha-value>)",
        "overlay-dark": "rgb(var(--rgb-overlay-dark) / <alpha-value>)"
},
      fontFamily: { sans: ["var(--font-sans)", "sans-serif"] },
      borderRadius: { sm: "var(--radius-sm)", md: "var(--radius-md)", lg: "var(--radius-lg)", xl: "var(--radius-xl)" },
    },
  },
  plugins: [],
} satisfies Config;
